Add new key binding such as number key and backspace
jpoon/vscode-typewriter pull request #3
Opened 2019-03-11 14:47 UTC by dollars0427

Dear jpoon,

I like this plugin as it can make my editor run like a typewriter. However, I found that the plugin had not bind some key such as "Tab", "Space" and "Backspace", so try to add these key to the plugin. 

Hope it is helpful ;)

Thank you !

2019-03-12 05:29 UTC, jpoon commented
Whoa, I hadn't realized somebody was actually using this; I built this thing as a fun random demo for a talk.

2019-03-14 06:05 UTC, jpoon requested changes

2019-03-14 06:05 UTC, jpoon commented on package.json
> +			{
Can you make these all one-line similar to original? Easier to review.

2019-03-14 09:07 UTC, dollars0427 commented on package.json
> +			{
No problem.
I made these all one-line similar to original now. Thank you :)

2019-03-17 05:02 UTC, jpoon approved these changes

2019-03-17 05:02 UTC, merged